name: macOS

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  xcode-12-4:
    runs-on: macos-11
    strategy:
      matrix:
        xcode: ['12.4']
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - name: Run CMake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build
      - name: Test skt executable
        run: cd build ; ctest -V
