name: Ubuntu

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run CMake
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug
    - name: Build
      run: cmake --build build
    - name: Test skt executable
      run: cd build ; ctest -V ; [ -s sktdoc.tex ] || exit 1